### ISSUE TITLE
Sparkling Water won't start when using PrintGCDetails java options

### ISSUE THREAD

**Issue by kjdoyle** [IBM/conductor-h2o-sparklingwater#5]
Sparkling Water stays in TENTATIVE then goes to ERROR state after 7 mins when PrintGCDetails is specified in the java options.

**Comment by kjdoyle** [comment]
This is happening because in the job monitor we do a grep -vi tail and the word Details contains tail preventing it from finding the port of the running Sparkling Water instance.

**Comment by mfeiman** [comment]
The issue has been resolved so closing it.
